### ISSUE TITLE
Panel doesn't scroll automatically when the cursor is at the bottom line

### ISSUE THREAD

**Issue by Konano** [hedgedoc/hedgedoc#862]
Version: 1.7.0

![image](https://user-images.githubusercontent.com/22500116/107324498-2113d380-6ae3-11eb-9072-7fc1a51a2c4c.png)
When I'm typing something in the bottom line(in pic is L341), the panel doesn't scroll automatically.

**Comment by ErikMichelson** [comment]
Seems to be the same thing as #80

**Comment by Lana-chan** [comment]
Still present in 1.7.1. The problem isn't only the lack of automatic scroll, but I cannot even _manually_ scroll to reveal my last line at all, making longform writing impossible. This has been an issue since the CodiMD days. 
![image](https://user-images.githubusercontent.com/9155588/107862442-a1ac3a00-6e2b-11eb-81d4-52400fd9bec7.png)

**Comment by DerMolly** [comment]
> Still present in 1.7.1. 

This was fixed in 1.7.2 (see https://github.com/hedgedoc/hedgedoc/releases/tag/1.7.2)

**Comment by Lana-chan** [comment]
Upgraded to 1.7.2, can confirm the scrolling works as expected now. Thanks for pointing out!

**Comment by DerMolly** [comment]
@Konano I'll close this now. Feel free to confirm here if it works with 1.7.2 for you too. Or reopen if you have further issues.

**Comment by Konano** [comment]
![image](https://user-images.githubusercontent.com/22500116/107983762-71b68f80-7001-11eb-8f0d-56e255098b4f.png)
But the problem still exists.

**Comment by DerMolly** [comment]
Could you give use a detailed step-by-step guide how you encounter this problem, @Konano?

**Comment by Konano** [comment]
![tmp](https://user-images.githubusercontent.com/22500116/107984593-32893e00-7003-11eb-8a93-2de24070bc0b.gif)
And I found that when I press F11 to enable full screen mode, the problem disappeared, works as expected.

**Comment by mrdrogdrog** [comment]
I don't know if we can fix this in 1.x. The CodeMirror-Scroll-Logic seems to clash with the existence of the bottom bar.

**Comment by davidmehren** [comment]
@hedgedoc/frontend does anyone still want to take a look at this to see if we can fix this with 1.8?
Otherwise, I would have to close the issue as won't fix :/

**Comment by mrdrogdrog** [comment]
Like i said: I'm not sure if this is possible without layout changes.

**Comment by mrdrogdrog** [comment]
Or rephrased:
I don't think that it's worth it to fix this in 1.8. The effort is to high.

**Comment by sijanec** [comment]
Well the editor is useless if you can't see what you're typing? Why was this closed?

Is there a workaround?

**Comment by mrdrogdrog** [comment]
Fixing this problem isn't as trivial as it seems because the HedgeDoc 1.x code is a huge mess. 
Right now we're rewriting the whole application, so 2.0 won't have this problem.

A possible work around is to add many blank lines to the end of the document.

**Comment by sijanec** [comment]
Thanks a lot for the comment! That makes sense, I'll stay tuned for 2.x
announcements.

For anyone else here, see the `develop` branch.

V V tor., 13. apr. 2021 ob 20:09 je oseba Tilman Vatteroth <
***@***.***> napisala:
